import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./@core/header";
import Footer from "./@core/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Natural",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-[100vh] flex flex-col justify-between">
          <div>
            <Header />
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
